package orgunit.e_shop;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class Address implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "ADDRESS_ID_GENERATOR")
   @javax.persistence.Id
   @javax.persistence.SequenceGenerator(sequenceName = "ADDRESS_ID_SEQ", name = "ADDRESS_ID_GENERATOR")
   private java.lang.Long id;

   @org.kie.api.definition.type.Label(value = "street")
   private java.lang.String street;

   @org.kie.api.definition.type.Label(value = "zip code")
   private int zipCode;

   @org.kie.api.definition.type.Label(value = "city")
   private java.lang.String city;

   @org.kie.api.definition.type.Label(value = "country")
   private java.lang.String country;

   public Address()
   {
   }

   public java.lang.Long getId()
   {
      return this.id;
   }

   public void setId(java.lang.Long id)
   {
      this.id = id;
   }

   public java.lang.String getStreet()
   {
      return this.street;
   }

   public void setStreet(java.lang.String street)
   {
      this.street = street;
   }

   public int getZipCode()
   {
      return this.zipCode;
   }

   public void setZipCode(int zipCode)
   {
      this.zipCode = zipCode;
   }

   public java.lang.String getCity()
   {
      return this.city;
   }

   public void setCity(java.lang.String city)
   {
      this.city = city;
   }

   public java.lang.String getCountry()
   {
      return this.country;
   }

   public void setCountry(java.lang.String country)
   {
      this.country = country;
   }

   public Address(java.lang.Long id, java.lang.String street, int zipCode,
         java.lang.String city, java.lang.String country)
   {
      this.id = id;
      this.street = street;
      this.zipCode = zipCode;
      this.city = city;
      this.country = country;
   }

}