package orgunit.e_shop;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class Name implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "NAME_ID_GENERATOR")
   @javax.persistence.Id
   @javax.persistence.SequenceGenerator(sequenceName = "NAME_ID_SEQ", name = "NAME_ID_GENERATOR")
   private java.lang.Long id;

   @org.kie.api.definition.type.Label(value = "first name")
   private java.lang.String firstName;

   @org.kie.api.definition.type.Label(value = "last name")
   private java.lang.String lastName;

   public Name()
   {
   }

   public java.lang.Long getId()
   {
      return this.id;
   }

   public void setId(java.lang.Long id)
   {
      this.id = id;
   }

   public java.lang.String getFirstName()
   {
      return this.firstName;
   }

   public void setFirstName(java.lang.String firstName)
   {
      this.firstName = firstName;
   }

   public java.lang.String getLastName()
   {
      return this.lastName;
   }

   public void setLastName(java.lang.String lastName)
   {
      this.lastName = lastName;
   }

   public Name(java.lang.Long id, java.lang.String firstName,
         java.lang.String lastName)
   {
      this.id = id;
      this.firstName = firstName;
      this.lastName = lastName;
   }

}