package orgunit.e_shop;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class Person implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "PERSON_ID_GENERATOR")
   @javax.persistence.Id
   @javax.persistence.SequenceGenerator(sequenceName = "PERSON_ID_SEQ", name = "PERSON_ID_GENERATOR")
   private java.lang.Long id;

   @javax.persistence.ManyToOne(cascade = { javax.persistence.CascadeType.ALL }, fetch = javax.persistence.FetchType.EAGER)
   @org.kie.api.definition.type.Label(value = "name")
   private orgunit.e_shop.Name name;

   @javax.persistence.ManyToOne(cascade = { javax.persistence.CascadeType.ALL }, fetch = javax.persistence.FetchType.EAGER)
   @org.kie.api.definition.type.Label(value = "address")
   private orgunit.e_shop.Address address;

   public Person()
   {
   }

   public java.lang.Long getId()
   {
      return this.id;
   }

   public void setId(java.lang.Long id)
   {
      this.id = id;
   }

   public orgunit.e_shop.Name getName()
   {
      return this.name;
   }

   public void setName(orgunit.e_shop.Name name)
   {
      this.name = name;
   }

   public orgunit.e_shop.Address getAddress()
   {
      return this.address;
   }

   public void setAddress(orgunit.e_shop.Address address)
   {
      this.address = address;
   }

   public Person(java.lang.Long id, orgunit.e_shop.Name name,
         orgunit.e_shop.Address address)
   {
      this.id = id;
      this.name = name;
      this.address = address;
   }

}