package orgunit.e_shop;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class Product implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "PRODUCT_ID_GENERATOR")
   @javax.persistence.Id
   @javax.persistence.SequenceGenerator(sequenceName = "PRODUCT_ID_SEQ", name = "PRODUCT_ID_GENERATOR")
   private java.lang.Long id;

   @org.kie.api.definition.type.Label(value = "name")
   private java.lang.String name;

   @org.kie.api.definition.type.Label(value = "price")
   private float price;

   @org.kie.api.definition.type.Label(value = "is available")
   private boolean isAvailable;

   @org.kie.api.definition.type.Label(value = "amount")
   private int amount;

   public Product()
   {
   }

   public java.lang.Long getId()
   {
      return this.id;
   }

   public void setId(java.lang.Long id)
   {
      this.id = id;
   }

   public java.lang.String getName()
   {
      return this.name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public float getPrice()
   {
      return this.price;
   }

   public void setPrice(float price)
   {
      this.price = price;
   }

   public boolean isIsAvailable()
   {
      return this.isAvailable;
   }

   public void setIsAvailable(boolean isAvailable)
   {
      this.isAvailable = isAvailable;
   }

   public int getAmount()
   {
      return this.amount;
   }

   public void setAmount(int amount)
   {
      this.amount = amount;
   }

   public Product(java.lang.Long id, java.lang.String name, float price,
         boolean isAvailable, int amount)
   {
      this.id = id;
      this.name = name;
      this.price = price;
      this.isAvailable = isAvailable;
      this.amount = amount;
   }

}