package orgunit.e_shop;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class Product implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "PRODUCT_ID_GENERATOR")
   @javax.persistence.Id
   @javax.persistence.SequenceGenerator(sequenceName = "PRODUCT_ID_SEQ", name = "PRODUCT_ID_GENERATOR")
   private java.lang.Long id;

   @org.kie.api.definition.type.Label("name")
   private java.lang.String name;

   @org.kie.api.definition.type.Label("price")
   private float price;

   public Product()
   {
   }

   public java.lang.Long getId()
   {
      return this.id;
   }

   public void setId(java.lang.Long id)
   {
      this.id = id;
   }

   public java.lang.String getName()
   {
      return this.name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public float getPrice()
   {
      return this.price;
   }

   public void setPrice(float price)
   {
      this.price = price;
   }

   public Product(java.lang.Long id, java.lang.String name, float price)
   {
      this.id = id;
      this.name = name;
      this.price = price;
   }

}