package orgunit.attendance;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Menu implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private boolean leave = false;
   private boolean timesheet = false;

   public Menu()
   {
   }

   public boolean isLeave()
   {
      return this.leave;
   }

   public void setLeave(boolean leave)
   {
      this.leave = leave;
   }

   public boolean isTimesheet()
   {
      return this.timesheet;
   }

   public void setTimesheet(boolean timesheet)
   {
      this.timesheet = timesheet;
   }

   public Menu(boolean leave, boolean timesheet)
   {
      this.leave = leave;
      this.timesheet = timesheet;
   }

}