package orgunit.attendance;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class Timesheet implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "TIMESHEET_ID_GENERATOR")
   @javax.persistence.Id
   @javax.persistence.SequenceGenerator(sequenceName = "TIMESHEET_ID_SEQ", name = "TIMESHEET_ID_GENERATOR")
   private java.lang.Long id;

   @org.kie.api.definition.type.Label("Line")
   @javax.persistence.ManyToOne(cascade = { javax.persistence.CascadeType.ALL }, fetch = javax.persistence.FetchType.EAGER)
   private orgunit.attendance.TimesheetLine line;

   @org.kie.api.definition.type.Label(value = "Is Editable")
   private java.lang.Boolean isEditable = true;

   public Timesheet()
   {
   }

   public java.lang.Long getId()
   {
      return this.id;
   }

   public void setId(java.lang.Long id)
   {
      this.id = id;
   }

   public orgunit.attendance.TimesheetLine getLine()
   {
      return this.line;
   }

   public void setLine(orgunit.attendance.TimesheetLine line)
   {
      this.line = line;
   }

   public java.lang.Boolean getIsEditable()
   {
      return this.isEditable;
   }

   public void setIsEditable(java.lang.Boolean isEditable)
   {
      this.isEditable = isEditable;
   }

   public Timesheet(java.lang.Long id, orgunit.attendance.TimesheetLine line,
         java.lang.Boolean isEditable)
   {
      this.id = id;
      this.line = line;
      this.isEditable = isEditable;
   }

}