package orgunit.attendance;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class TimesheetEditor implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "TIMESHEETEDITOR_ID_GENERATOR")
   @javax.persistence.Id
   @javax.persistence.SequenceGenerator(sequenceName = "TIMESHEETEDITOR_ID_SEQ", name = "TIMESHEETEDITOR_ID_GENERATOR")
   private java.lang.Long id;

   @javax.persistence.ManyToOne(cascade = { javax.persistence.CascadeType.ALL }, fetch = javax.persistence.FetchType.EAGER)
   @org.kie.api.definition.type.Label(value = "Timesheet")
   private orgunit.attendance.Timesheet timesheet;

   public TimesheetEditor()
   {
   }

   public java.lang.Long getId()
   {
      return this.id;
   }

   public void setId(java.lang.Long id)
   {
      this.id = id;
   }

   public orgunit.attendance.Timesheet getTimesheet()
   {
      return this.timesheet;
   }

   public void setTimesheet(orgunit.attendance.Timesheet timesheet)
   {
      this.timesheet = timesheet;
   }

   public TimesheetEditor(java.lang.Long id,
         orgunit.attendance.Timesheet timesheet)
   {
      this.id = id;
      this.timesheet = timesheet;
   }

}