package orgunit.attendance;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class TimesheetLine implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "TIMESHEET_ID_GENERATOR")
   @javax.persistence.Id
   @javax.persistence.SequenceGenerator(sequenceName = "TIMESHEET_ID_SEQ", name = "TIMESHEET_ID_GENERATOR")
   private java.lang.Long id;

   @org.kie.api.definition.type.Label(value = "Date")
   private java.util.Date date;

   @org.kie.api.definition.type.Label(value = "Type")
   private java.lang.String type;

   @org.kie.api.definition.type.Label(value = "In Time")
   private java.lang.String inTime;

   @org.kie.api.definition.type.Label(value = "Out Time")
   private java.lang.String outTime;

   @org.kie.api.definition.type.Label(value = "Break Duration")
   private java.lang.String breakDuration;

   @org.kie.api.definition.type.Label(value = "Total Work")
   private java.lang.String totalWork;

   public TimesheetLine()
   {
   }

   public java.lang.Long getId()
   {
      return this.id;
   }

   public void setId(java.lang.Long id)
   {
      this.id = id;
   }

   public java.util.Date getDate()
   {
      return this.date;
   }

   public void setDate(java.util.Date date)
   {
      this.date = date;
   }

   public java.lang.String getType()
   {
      return this.type;
   }

   public void setType(java.lang.String type)
   {
      this.type = type;
   }

   public java.lang.String getInTime()
   {
      return this.inTime;
   }

   public void setInTime(java.lang.String inTime)
   {
      this.inTime = inTime;
   }

   public java.lang.String getOutTime()
   {
      return this.outTime;
   }

   public void setOutTime(java.lang.String outTime)
   {
      this.outTime = outTime;
   }

   public java.lang.String getBreakDuration()
   {
      return this.breakDuration;
   }

   public void setBreakDuration(java.lang.String breakDuration)
   {
      this.breakDuration = breakDuration;
   }

   public java.lang.String getTotalWork()
   {
      return this.totalWork;
   }

   public void setTotalWork(java.lang.String totalWork)
   {
      this.totalWork = totalWork;
   }

   public TimesheetLine(java.lang.Long id, java.util.Date date,
         java.lang.String type, java.lang.String inTime,
         java.lang.String outTime, java.lang.String breakDuration,
         java.lang.String totalWork)
   {
      this.id = id;
      this.date = date;
      this.type = type;
      this.inTime = inTime;
      this.outTime = outTime;
      this.breakDuration = breakDuration;
      this.totalWork = totalWork;
   }

}