package orgunit.testproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class testobject implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "TESTDO_ID_GENERATOR")
   @javax.persistence.Id
   @javax.persistence.SequenceGenerator(sequenceName = "TESTDO_ID_SEQ", name = "TESTDO_ID_GENERATOR")
   private java.lang.Long id;

   @org.kie.api.definition.type.Label("Name")
   private java.lang.String name;

   @org.kie.api.definition.type.Label(value = "Number")
   private int number;

   @org.kie.api.definition.type.Label(value = "Date")
   private java.util.Date date;

   @org.kie.api.definition.type.Label(value = "time")
   private java.lang.String time;

   @org.kie.api.definition.type.Label(value = "person")
   private java.lang.String person;

   @org.kie.api.definition.type.Label(value = "address")
   private java.lang.String address;

   public testobject()
   {
   }

   public java.lang.Long getId()
   {
      return this.id;
   }

   public void setId(java.lang.Long id)
   {
      this.id = id;
   }

   public java.lang.String getName()
   {
      return this.name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public int getNumber()
   {
      return this.number;
   }

   public void setNumber(int number)
   {
      this.number = number;
   }

   public java.util.Date getDate()
   {
      return this.date;
   }

   public void setDate(java.util.Date date)
   {
      this.date = date;
   }

   public java.lang.String getTime()
   {
      return this.time;
   }

   public void setTime(java.lang.String time)
   {
      this.time = time;
   }

   public java.lang.String getPerson()
   {
      return this.person;
   }

   public void setPerson(java.lang.String person)
   {
      this.person = person;
   }

   public java.lang.String getAddress()
   {
      return this.address;
   }

   public void setAddress(java.lang.String address)
   {
      this.address = address;
   }

   public testobject(java.lang.Long id, java.lang.String name, int number,
         java.util.Date date, java.lang.String time, java.lang.String person,
         java.lang.String address)
   {
      this.id = id;
      this.name = name;
      this.number = number;
      this.date = date;
      this.time = time;
      this.person = person;
      this.address = address;
   }

}